/* Criando o Banco de dados e utilizando */
CREATE DATABASE `NBA_STATICS`;
USE `NBA_STATICS`;

/* Estrutura da tabela Times */
CREATE TABLE `TIMES` (
  `TIME_ID` INT PRIMARY KEY,
  `LIGA_ID` INT,
  `ABREVIACAO` CHAR(3),
  `NOME_TIME` VARCHAR(50),
  `ANO_FUNDACAO` INT(4),
  `CIDADE` VARCHAR(50),
  `ARENA` VARCHAR(100),
  `CAPACIDADE_ARENA` INT,
  `PROPRIETARIO_TIME` VARCHAR(100),
  `DIRETOR_GERAL` VARCHAR(100),
  `TREINADOR` VARCHAR(100),
  `CLUBE_AFILIADO` VARCHAR(100)
);

/* Estrutura da tabela Classificacao */
CREATE TABLE `CLASSIFICACAO` (
  `TIME_ID` INT,
  `LIGA_ID` INT,
  `TEMPORADA` INT,
  `DATA_POSICAO` DATE,
  `CONFERENCIA` VARCHAR(10),
  `JOGOS` INT,
  `VITORIAS` INT,
  `DERROTAS` INT,
  `PCT_VITORIAS` DECIMAL(5,3),
  `RECORDES_CASA` VARCHAR(6),
  `RECORDES_FORA` VARCHAR(6)
);

/* Estrutura da tabela Jogos */
CREATE TABLE `JOGOS` (
  `DATA_JOGO` DATE,
  `JOGO_ID` INT PRIMARY KEY,
  `JOGO_STATUS` CHAR(5),
  `TIME_CASA_ID` INT,
  `TIME_VISITANTE_ID` INT,
  `TEMPORADA` INT,
  `PONTOS_CASA` INT,
  `PCT_FG_CASA` DECIMAL(4,1),
  `PCT_FT_CASA` DECIMAL(4,1),
  `PCT_FG3_CASA` DECIMAL(4,1),
  `AST_CASA` DECIMAL(4,1),
  `REB_CASA` DECIMAL(4,1),
  `PONTOS_VISITANTE` INT,
  `PCT_FG_VISITANTE` DECIMAL(4,1),
  `PCT_FT_VISITANTE` DECIMAL(4,1),
  `PCT_FG3_VISITANTE` DECIMAL(4,1),
  `AST_VISITANTE` DECIMAL(4,1),
  `REB_VISITANTE` DECIMAL(4,1),
  `TIME_CASA_VENCE` CHAR(1)
);

/* Estrutura da tabela Jogador */
CREATE TABLE `JOGADOR` (
  `NOME_JOGADOR` VARCHAR(100),
  `TIME_ID` INT,
  `JOGADOR_ID` INT PRIMARY KEY,
  `TEMPORADA` INT
);

/* Criando as Foreign Key nas tabelas */
SET foreign_key_checks = 0;
ALTER TABLE `JOGADOR` ADD CONSTRAINT `FK_TIME_ID` FOREIGN KEY (`TIME_ID`) REFERENCES `TIMES` (`TIME_ID`);
ALTER TABLE `JOGOS` ADD CONSTRAINT `FK_TIME_CASA_ID` FOREIGN KEY(`TIME_CASA_ID`) REFERENCES `TIMES`(`TIME_ID`);
ALTER TABLE `JOGOS` ADD CONSTRAINT `FK_TIME_VISITANTE_ID` FOREIGN KEY(`TIME_VISITANTE_ID`) REFERENCES `TIMES`(`TIME_ID`);
ALTER TABLE `CLASSIFICACAO` ADD CONSTRAINT `FK_TIME_CLASS_ID` FOREIGN KEY(`TIME_ID`) REFERENCES `TIMES`(`TIME_ID`);

/* Updates para melhor visualização dos dados */
UPDATE CLASSIFICACAO SET TEMPORADA = 2019
WHERE TEMPORADA = 12019;
UPDATE CLASSIFICACAO SET TEMPORADA = 2019
WHERE TEMPORADA = 22019;
UPDATE CLASSIFICACAO SET TEMPORADA = 2018
WHERE TEMPORADA = 12018;
UPDATE CLASSIFICACAO SET TEMPORADA = 2018
WHERE TEMPORADA = 22018;
UPDATE CLASSIFICACAO SET TEMPORADA = 2017
WHERE TEMPORADA = 12017;
UPDATE CLASSIFICACAO SET TEMPORADA = 2017
WHERE TEMPORADA = 22017;
UPDATE CLASSIFICACAO SET TEMPORADA = 2016
WHERE TEMPORADA = 12016;
UPDATE CLASSIFICACAO SET TEMPORADA = 2016
WHERE TEMPORADA = 22016;
UPDATE CLASSIFICACAO SET TEMPORADA = 2015
WHERE TEMPORADA = 12015;
UPDATE CLASSIFICACAO SET TEMPORADA = 2015
WHERE TEMPORADA = 22015;
UPDATE CLASSIFICACAO SET TEMPORADA = 2014
WHERE TEMPORADA = 12014;
UPDATE CLASSIFICACAO SET TEMPORADA = 2014
WHERE TEMPORADA = 22014;
UPDATE CLASSIFICACAO SET TEMPORADA = 2013
WHERE TEMPORADA = 12013;
UPDATE CLASSIFICACAO SET TEMPORADA = 2013
WHERE TEMPORADA = 22013;
UPDATE CLASSIFICACAO SET TEMPORADA = 2012
WHERE TEMPORADA = 12012;
UPDATE CLASSIFICACAO SET TEMPORADA = 2012
WHERE TEMPORADA = 22012;
UPDATE CLASSIFICACAO SET TEMPORADA = 2011
WHERE TEMPORADA = 12011;
UPDATE CLASSIFICACAO SET TEMPORADA = 2011
WHERE TEMPORADA = 22011;
UPDATE CLASSIFICACAO SET TEMPORADA = 2010
WHERE TEMPORADA = 12010;
UPDATE CLASSIFICACAO SET TEMPORADA = 2010
WHERE TEMPORADA = 22010;
UPDATE CLASSIFICACAO SET TEMPORADA = 2009
WHERE TEMPORADA = 12009;
UPDATE CLASSIFICACAO SET TEMPORADA = 2009
WHERE TEMPORADA = 22009;
UPDATE CLASSIFICACAO SET TEMPORADA = 2008
WHERE TEMPORADA = 12008;
UPDATE CLASSIFICACAO SET TEMPORADA = 2008
WHERE TEMPORADA = 22008;
UPDATE CLASSIFICACAO SET TEMPORADA = 2007
WHERE TEMPORADA = 12007;
UPDATE CLASSIFICACAO SET TEMPORADA = 2007
WHERE TEMPORADA = 22007;
UPDATE CLASSIFICACAO SET TEMPORADA = 2006
WHERE TEMPORADA = 12006;
UPDATE CLASSIFICACAO SET TEMPORADA = 2006
WHERE TEMPORADA = 22006;
UPDATE CLASSIFICACAO SET TEMPORADA = 2005
WHERE TEMPORADA = 12005;
UPDATE CLASSIFICACAO SET TEMPORADA = 2005
WHERE TEMPORADA = 22005;
UPDATE CLASSIFICACAO SET TEMPORADA = 2004
WHERE TEMPORADA = 12004;
UPDATE CLASSIFICACAO SET TEMPORADA = 2004
WHERE TEMPORADA = 22004;
UPDATE CLASSIFICACAO SET TEMPORADA = 2003
WHERE TEMPORADA = 12003;
UPDATE CLASSIFICACAO SET TEMPORADA = 2003
WHERE TEMPORADA = 22003;

/* Insert de dados que não foram carregados */
INSERT INTO TIMES VALUES(1610612740,00,'NOP','Pelicans',2002,'New Orleans','Smoothie King Center',17791,'Tom Benson','Trajan Langdon','Alvin Gentry','No Affiliate');
INSERT INTO TIMES VALUES(1610612751,00,'BKN','Nets',1976,'Brooklyn','Barclays Center',19000,'Joe Tsai','Sean Marks','Kenny Atkinson','Long Island Nets');
INSERT INTO TIMES VALUES(1610612755,00,'PHI','76ers',1949,'Philadelphia','Wells Fargo Center',19500,'Joshua Harris','Elton Brand','Brett Brown','Delaware Blue Coats');
INSERT INTO TIMES VALUES(1610612756,00,'PHX','Suns',1968,'Phoenix','Talking Stick Resort Arena',18422,'Robert Sarver','James Jones','Monty Williams','Northern Arizona Suns');


/* GLOSSÁRIO */
/*
PCT_FG - % Arremessos certos
PCT_FT - % Aproveitamento nos lances livres
PCT_FG3 - % de Arremessos de 3 pontos convertidos
AST - Assistência por jogo
MIN_QUADRA - Tempo do jogador em quadra em minutos
FGM - Média de arremessos convertidos
FGA - Média de Tentativas de arremessos
FG3M - Média de Arremessos de 3 pontos convertidos
FG3A - Média de Tentativas de arremessos de 3 pontos
FTM - Média de Lances Livres convertidos
FTA - Média de Tentativas de lances livres
REB - Rebotes por jogo
BLK - Tocos por jogo
PTS - Pontos por jogo
*/

 







