/* PERGUNTAS */
/* 1 - Quais times tem na NBA */
SELECT ABREVIACAO, CIDADE, NOME_TIME, ANO_FUNDACAO, ARENA, TREINADOR FROM TIMES;

/* 2 - Times mais antigo */
SELECT NOME_TIME, ANO_FUNDACAO FROM TIMES
WHERE ANO_FUNDACAO = (SELECT MIN(ANO_FUNDACAO) FROM TIMES);

/* 2.a - Times mais novos */
SELECT NOME_TIME, ANO_FUNDACAO FROM TIMES
WHERE ANO_FUNDACAO = (SELECT MAX(ANO_FUNDACAO) FROM TIMES);

/* 3 - As 5 maiores Arenas */
SELECT NOME_TIME, ARENA, CAPACIDADE_ARENA FROM TIMES
WHERE CAPACIDADE_ARENA > 0
ORDER BY CAPACIDADE_ARENA DESC LIMIT 5;

/* 4 - 5 melhores times de cada conferencia na temporada 2018? */
/* 4.a - Conferencia EAST*/
SELECT CIDADE, NOME_TIME, TEMPORADA, CONFERENCIA, JOGOS, VITORIAS, DERROTAS FROM CLASSIFICACAO
INNER JOIN TIMES USING(TIME_ID)
WHERE TEMPORADA = 2018 AND CONFERENCIA LIKE 'EAST'
GROUP BY NOME_TIME
LIMIT 5;

/* 4.b - Conferencia WEST*/
SELECT CIDADE, NOME_TIME, TEMPORADA, CONFERENCIA, JOGOS, VITORIAS, DERROTAS FROM CLASSIFICACAO
INNER JOIN TIMES USING(TIME_ID)
WHERE TEMPORADA = 2018 AND CONFERENCIA LIKE 'WEST'
GROUP BY NOME_TIME
LIMIT 5;

/* 5 - Jogadores dos times de cada Conferencia no ano de 2018*/
/* 5.a - Conferencia EAST */
SELECT T.CIDADE, T.NOME_TIME, J.NOME_JOGADOR, C.TEMPORADA, C.CONFERENCIA FROM CLASSIFICACAO C
INNER JOIN TIMES T ON C.TIME_ID = T.TIME_ID
INNER JOIN JOGADOR J ON J.TIME_ID = T.TIME_ID
WHERE C.TEMPORADA = 2018 AND C.CONFERENCIA LIKE 'EAST'
GROUP BY J.NOME_JOGADOR;

/* 5.b - Conferencia WEST */
SELECT T.CIDADE, T.NOME_TIME, J.NOME_JOGADOR, C.TEMPORADA, C.CONFERENCIA FROM CLASSIFICACAO C
INNER JOIN TIMES T ON C.TIME_ID = T.TIME_ID
INNER JOIN JOGADOR J ON J.TIME_ID = T.TIME_ID
WHERE C.TEMPORADA = 2018 AND C.CONFERENCIA LIKE 'WEST'
GROUP BY J.NOME_JOGADOR;

/* 6 - TOP 10 Pontuações do Time da Casa */
SELECT NOME_TIME, B.MAX AS PONTOS FROM
	(SELECT TEMPORADA, MAX(MAX_PTS) AS MAX FROM
		(SELECT JOGOS.TIME_CASA_ID, TIMES.NOME_TIME, JOGOS.TEMPORADA, MAX(CAST(JOGOS.PONTOS_CASA AS UNSIGNED)) AS MAX_PTS FROM TIMES
        INNER JOIN JOGOS ON JOGOS.TIME_CASA_ID = TIMES.TIME_ID
        GROUP BY JOGOS.TIME_CASA_ID, TIMES.NOME_TIME, JOGOS.TEMPORADA
        ORDER BY MAX_PTS DESC, JOGOS.TEMPORADA) AS TEMPORADA
        GROUP BY TEMPORADA) AS A
			LEFT JOIN 
            (SELECT TEMPORADA, MAX(MAX_PTS) AS MAX, NOME_TIME, TIME_CASA_ID FROM
				(SELECT TIME_CASA_ID, NOME_TIME, TEMPORADA, MAX(CAST(PONTOS_CASA AS UNSIGNED)) AS MAX_PTS FROM TIMES
                INNER JOIN JOGOS ON JOGOS.TIME_CASA_ID = TIMES.TIME_ID
                GROUP BY TEMPORADA, TIME_CASA_ID, NOME_TIME
                ORDER BY MAX_PTS DESC, TEMPORADA) AS TEMPORADA
                GROUP BY TEMPORADA, NOME_TIME, TIME_CASA_ID) AS B ON A.MAX = B.MAX AND A.TEMPORADA = B.TEMPORADA
ORDER BY PONTOS DESC LIMIT 10;





